name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check code
        uses: actions/checkout@v6

      - name: set node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dep
        run: npm ci

      - name: build
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/notely-503116/notely-ar-repo/notely:latest .


      - name: migrate
        run: npm run db:migrate

      - name: Deploy to Cloud run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-503116/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-503116 --max-instances=4
