name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v6

      - name: set node
        uses: action/setup-node@v5
        with:
          node-version: 22

      - name: Install dep
        run: npm ci

      - name: build
        run: npm run build
